/* Generated By:JavaCC: Do not edit this line. ABDLParserConstants.java */
package abdl;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ABDLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LCB = 5;
  /** RegularExpression Id. */
  int RCB = 6;
  /** RegularExpression Id. */
  int LB = 7;
  /** RegularExpression Id. */
  int RB = 8;
  /** RegularExpression Id. */
  int QT = 9;
  /** RegularExpression Id. */
  int ADDRESSBOOK = 10;
  /** RegularExpression Id. */
  int PERSON = 11;
  /** RegularExpression Id. */
  int ADDRESS = 12;
  /** RegularExpression Id. */
  int BIRTHDATE = 13;
  /** RegularExpression Id. */
  int PHONE = 14;
  /** RegularExpression Id. */
  int EMAIL = 15;
  /** RegularExpression Id. */
  int ABDLNAME = 16;
  /** RegularExpression Id. */
  int PERSONNAME = 17;
  /** RegularExpression Id. */
  int ADDRESSLINE = 18;
  /** RegularExpression Id. */
  int EMAIL_ADDRESS = 19;
  /** RegularExpression Id. */
  int USER = 20;
  /** RegularExpression Id. */
  int HOST = 21;
  /** RegularExpression Id. */
  int PHONE_NUM = 22;
  /** RegularExpression Id. */
  int EXT = 23;
  /** RegularExpression Id. */
  int DATE = 24;
  /** RegularExpression Id. */
  int MONTH = 25;
  /** RegularExpression Id. */
  int DAY = 26;
  /** RegularExpression Id. */
  int YEAR = 27;
  /** RegularExpression Id. */
  int TYPE = 28;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_ADDRESSBOOK = 1;
  /** Lexical state. */
  int IN_PERSON = 2;
  /** Lexical state. */
  int IN_ADDRESS = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"\\\"\"",
    "\"addressbook\"",
    "\"person\"",
    "\"address\"",
    "\"birthdate\"",
    "\"phone\"",
    "\"email\"",
    "<ABDLNAME>",
    "<PERSONNAME>",
    "<ADDRESSLINE>",
    "<EMAIL_ADDRESS>",
    "<USER>",
    "<HOST>",
    "<PHONE_NUM>",
    "<EXT>",
    "<DATE>",
    "<MONTH>",
    "<DAY>",
    "<YEAR>",
    "<TYPE>",
  };

}
