/* Generated By:JavaCC: Do not edit this line. ABDLParserConstants.java */
package abdl;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ABDLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ADDRESSBOOK = 5;
  /** RegularExpression Id. */
  int PERSON = 6;
  /** RegularExpression Id. */
  int BIRTHDATE = 7;
  /** RegularExpression Id. */
  int PHONE = 8;
  /** RegularExpression Id. */
  int EMAIL = 9;
  /** RegularExpression Id. */
  int ADDRESS = 10;
  /** RegularExpression Id. */
  int LB = 11;
  /** RegularExpression Id. */
  int RB = 12;
  /** RegularExpression Id. */
  int MONTH = 13;
  /** RegularExpression Id. */
  int LOL = 14;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"addressbook\"",
    "\"person\"",
    "\"birthdate\"",
    "\"phone\"",
    "\"email\"",
    "\"address\"",
    "\"{\"",
    "\"}\"",
    "<MONTH>",
    "\"lol\"",
  };

}
