/**
 * JavaCC template file created by SF JavaCC plugin 1.5.17+ wizard for JavaCC 1.5.0+
 */options{  JDK_VERSION = "1.5";  static = false;}PARSER_BEGIN(ABDLParser)package abdl;public class ABDLParser{}PARSER_END(ABDLParser)SKIP :{  " "| "\r"| "\t"| "\n"}TOKEN : // KEYWORDS{  < ADDRESSBOOK : "addressbook" >| < PERSON : "person" >| < BIRTHDATE : "birthdate" >| < PHONE : "phone" >| < EMAIL : "email" >| < ADDRESS : "address" >}TOKEN :{  < LB : "{" >| < RB : "}" >}TOKEN : // MONTHS{  < MONTH :    "January"  | "February"  | "March"  | "April"  | "May"  | "June"  | "July"  | "August"  | "September"  | "October"  | "November"  | "December" >}

TOKEN: //test
{
  < LOL: "lol" >}void AddressBook() :{}{
  < LOL ><EOF >}void AddressLine() :{}{
  < MONTH >}